### ISSUE TITLE
werkzeug 모듈 관련 오류에 대한 문의입니다.

### ISSUE THREAD

**Issue by ChaeWonIm0** [gureuso/flask-movie#1]
안녕하세요! "처음 배우는 플라스크 웹 프로그래밍"을 즐겁게 읽고 있는 독자입니다.

다름이 아니라, 애플리케이션을 직접 만들면서 따라해보고 싶은데, 여러가지 모듈이 계속 작동하지 않아서 문제가 되고 있습니다.

2장의 [플라스크로 애플리케이션 만들기] 페이지 61에서 python manage.py db migrate를 시도했을 때, safe_str_cmp가 없다고 하여, 안되고 있습니다. 

오류 내용은 아래와 같습니다.

C:\myproject\helloflask\myproject\flask (main -> origin)
(venv) λ ython manage.py db migrate           
Traceback (most recent call last):
  File "C:\myproject\helloflask\myproject\flask\manage.py", line 16, in <module>
    from apps.controllers.router import app as application
  File "C:\myproject\helloflask\myproject\flask\apps\controllers\router.py", line 11, in <module>
    BlueprintRegister(app=app, module_path='apps.controllers', controller_name='controllers').register()
  File "C:\myproject\helloflask\myproject\flask\apps\common\register.py", line 20, in register
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myproject\helloflask\myproject\flask\apps\controllers\test\controllers.py", line 8, in <module>
    from .forms import TestForm
  File "C:\myproject\helloflask\myproject\flask\apps\controllers\test\forms.py", line 2, in <module>
    from flask_wtf import FlaskForm
  File "C:\myproject\helloflask\myproject\flask\venv\Lib\site-packages\flask_wtf\__init__.py", line 3, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "C:\myproject\helloflask\myproject\flask\venv\Lib\site-packages\flask_wtf\csrf.py", line 10, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (C:\myproject\helloflask\myproject\flask\venv\Lib\site-packages\werkzeug\security.py)

혹시 여기에 남겨도 확인해주실지 모르겠사오나...혹시나 하는 마음에 남겨봅니다.ㅠㅠㅠ

**Comment by gureuso** [comment]
안녕하세요. 해결 후 말씀드리겠습니다.

2023년 4월 16일 (일) 오후 5:36, Chae Won Im ***@***.***>님이 작성:

**Comment by gureuso** [comment]
안녕하세요. 플라스크 저자 윤정현입니다.

플라스크 버전이 많이 바뀌어 에러가 나고 있었습니다.

git pull origin main
pip uninstall -r requirements.txt
pip install -r requirements.txt

하신 다음

https://github.com/gureuso/flask

README를 참고하셔서 진행하시면 될것 같습니다.

2023년 4월 16일 (일) 오후 5:38, 구르소 ***@***.***>님이 작성:

**Comment by ChaeWonIm0** [comment]
와 넵 감사합니다!
